cat("\n||| LOADING LIBRARIES |||\n")


suppressPackageStartupMessages({
  library(shinydashboard)
  library(rhandsontable)
  library(shinyWidgets)
  library(DT)
  # library(readxl)
  # library(MASS)
  # library(plotly)
  # library(reshape2)
  # library(ggplot2)
  # library(drc)
  # library(tidyr)
  # library(dplyr)
  # library(shiny)
  # library(shinythemes)
  # library(XML)
  # library(tidyverse)
  # library(RColorBrewer)
  # library(shinyalert)
  # library(data.table)
  # library(shinyjs)
  # library(ggfittext)
  # library(writexl)
  # library(Cairo)
  # library(stringi)
  #library(shinytest)
})